//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boutique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Members
    {
        public int gm_id { get; set; }
        public Nullable<int> g_id { get; set; }
        public string gm_name { get; set; }
        public string gm_gender { get; set; }
        public string gm_agegroup { get; set; }
        public Nullable<int> gm_length { get; set; }
        public Nullable<int> gm_width { get; set; }
        public Nullable<int> gm_shoulder_len { get; set; }
        public Nullable<int> gm_sleeve_len { get; set; }
        public Nullable<int> gm_collor { get; set; }
        public Nullable<int> gm_full_len { get; set; }
        public Nullable<int> gm_chest { get; set; }
        public Nullable<int> gm_bottom { get; set; }
        public Nullable<int> gm_ankle_len { get; set; }
    }
}
