//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boutique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int g_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string g_name { get; set; }
        public string g_type { get; set; }
    }
}
