//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boutique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Orders
    {
        public int po_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string fullname { get; set; }
        public string date { get; set; }
        public string contactno { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string zipcode { get; set; }
        public string p_name { get; set; }
        public string p_category { get; set; }
        public string p_description { get; set; }
        public Nullable<int> p_qty { get; set; }
        public string p_size { get; set; }
        public string p_price { get; set; }
    }
}
