//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boutique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stich_Products
    {
        public int sp_id { get; set; }
        public string sp_name { get; set; }
        public string sp_category { get; set; }
        public string sp_description { get; set; }
        public Nullable<int> sp_avbqty { get; set; }
        public string sp_image { get; set; }
        public string sp_size { get; set; }
        public Nullable<int> sp_price { get; set; }
    }
}
