//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boutique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unstich_Product_Orders
    {
        public int uspo_id { get; set; }
        public Nullable<int> usp_id { get; set; }
        public Nullable<int> uspo_length { get; set; }
        public Nullable<int> uspo_width { get; set; }
        public Nullable<int> uspo_shoulder_len { get; set; }
        public Nullable<int> uspo_sleeve_len { get; set; }
        public Nullable<int> uspo_collor { get; set; }
        public Nullable<int> uspo_full_len { get; set; }
        public Nullable<int> uspo_chest { get; set; }
        public Nullable<int> uspo_bottom { get; set; }
        public Nullable<int> uspo_ankle_len { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> gm_id { get; set; }
        public Nullable<int> uspo_req_status { get; set; }
        public Nullable<int> uspo_ds_id { get; set; }
        public string uspo_date { get; set; }
    }
}
