//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boutique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unstich_Products
    {
        public int usp_id { get; set; }
        public string usp_name { get; set; }
        public Nullable<int> usp_size { get; set; }
        public string usp_category { get; set; }
        public string usp_description { get; set; }
        public Nullable<int> usp_avbqty { get; set; }
        public string usp_image { get; set; }
        public Nullable<int> usp_price { get; set; }
    }
}
